---
# tasks file for ansible_lint
- name: test veriables and environment
  assert:
    that:

- name: install ansible_lint
  pip:
    name: "{{ ansible_lint_packages }}"
    state: present
  register: ansible_lint_install_ansible_lint
  until: ansible_lint_install_ansible_lint is succeeded
  retries: 3
